# Generated by Django 3.2.9 on 2021-12-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20211206_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='filename',
            field=models.CharField(default='1638786028.301266.pdf', max_length=255, verbose_name='Nom du fichier'),
            preserve_default=False,
        ),
    ]
