# Generated by Django 3.2.9 on 2021-12-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_bon_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=19, verbose_name='Tva'),
            preserve_default=False,
        ),
    ]
