# Generated by Django 3.2.9 on 2021-12-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_bon_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(max_length=30, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='priceHT',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Montant H.T. (par mise en ligne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='totalHT',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total H.T. (de la campagne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='totalTTC',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total T.T.C. (par mise en ligne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Tva'),
        ),
    ]
