# Generated by Django 3.2.9 on 2022-01-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20211207_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='adresseComplement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Complément d'adresse"),
        ),
        migrations.AlterField(
            model_name='bon',
            name='autoNumerotation',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Numérotation automatique'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='bdcLocality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localité / Ville'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='commercialContact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact commercial'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='editionDomTom',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Edition DOM/TOM '),
        ),
        migrations.AlterField(
            model_name='bon',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (obligatoire)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='encart',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Encart'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='firstDeploy',
            field=models.DateField(blank=True, null=True, verbose_name='Première mise en ligne programmée le'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='nonReductibleCommand',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Commande non reconductible '),
        ),
        migrations.AlterField(
            model_name='bon',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='phoneOrFax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone / Fax'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='portable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Portable'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='postalCode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='priceHT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Montant H.T. (par mise en ligne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='representedBy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Représentée par'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='bon',
            name='socialReason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='totalHT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total H.T. (de la campagne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='totalTTC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total T.T.C. (par mise en ligne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Tva'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
