# Generated by Django 3.2.9 on 2022-01-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_entreprise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entreprise',
        ),
    ]
