# Generated by Django 3.2.9 on 2022-01-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_delete_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='priceHT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant H.T. (par mise en ligne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='totalHT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total H.T. (de la campagne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='totalTTC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total T.T.C. (par mise en ligne)'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tva'),
        ),
    ]
