# Generated by Django 3.2.9 on 2022-01-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20220124_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='firstDeploy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Première mise en ligne programmée le'),
        ),
    ]
