# Generated by Django 3.2.9 on 2021-12-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Nom')),
                ('lastname', models.CharField(max_length=255, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=255, verbose_name='Téléphone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
