# Generated by Django 3.2.9 on 2023-02-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_entreprise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='photoLink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien de la photo'),
        ),
    ]
